sqrl-parser/src/main/java/com/datasqrl/parse/AstBuilder.java
sqrl-planner/src/test/java/com/datasqrl/plan/local/analyze/AnalyzerTest.java
sqrl-planner/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/AnalyzerTest/stringLiteral.txt

Resolves #141
Signed-off-by: Daniel Henneberger <git@danielhenneberger.com>

Unquote string literals

---

sqrl-common/src/main/java/com/datasqrl/plan/calcite/util/CalciteUtil.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/AbstractSqlNodeFactory.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/ConvertTimestampToExpression.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/SqlNodeFactory.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/SqlTransformer.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/SqlTransformerFactory.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/Transpiler.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/AddContextFields.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/AddContextTable.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/AddHints.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/AnalyzeStatement.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/FlattenFieldPaths.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/FlattenTablePaths.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/QualifyIdentifiers.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/transpile/ReplaceWithVirtualTable.java
sqrl-planner/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/invalidRootExpressionTest.txt

No changes here, just a quick code cleanup.

Clean up code for transpiler

---

sqrl-engine-flink/src/main/java/com/datasqrl/engine/stream/flink/plan/FlinkPhysicalPlanRewriter.java

I was reading through this class and I refactored it slightly.

Slight refactor of FlinkPhysicalPlanRewriter

---

docker-compose.dev.yml
sqrl-common/src/main/java/com/datasqrl/loaders/Deserializer.java
sqrl-common/src/main/java/com/datasqrl/loaders/ResourceResolver.java
sqrl-common/src/main/java/com/datasqrl/util/FileUtil.java
sqrl-compiler/src/main/java/com/datasqrl/compile/Compiler.java
sqrl-compiler/src/test/java/com/datasqrl/compile/ConfigurationTest.java
sqrl-engine-core/src/main/java/com/datasqrl/config/GlobalEngineConfiguration.java
sqrl-examples/udf/myudf.sqrl
sqrl-io-core/src/main/java/com/datasqrl/io/tables/TableSchemaFactory.java
sqrl-loader-core/src/main/java/com/datasqrl/loaders/ObjectLoaderImpl.java
sqrl-loader-core/src/main/java/com/datasqrl/loaders/TableSourceNamespaceObject.java
sqrl-packager/src/main/resources/build.gradle
sqrl-parser/pom.xml
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/ClasspathResourceResolver.java
sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/FileResourceResolver.java
sqrl-run/src/main/java/com/datasqrl/FlinkMain.java
sqrl-run/src/main/java/com/datasqrl/cmd/AbstractCompilerCommand.java
sqrl-run/src/main/java/com/datasqrl/cmd/DiscoverCommand.java
sqrl-run/src/main/java/com/datasqrl/cmd/ServeCommand.java
sqrl-schemas/sqrl-schema-flexible/src/main/java/com/datasqrl/schema/input/FlexibleTableSchemaFactory.java

Allows resolving all resources via jar.

Allow resource loading via JAR

---

sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/config/CompilerConfiguration.java

Renamed config option debugTables

---

sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/DocumentationExamplesTest.java
sqrl-tools/sqrl-packager/src/test/java/com/datasqrl/packager/repository/RepositoryTest.java

Re-enable repo tests

---

sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/inference/SchemaInference.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/SchemaInferenceTest.java

See test cases for the common use cases.

Allow alternate view for graphql queries via more schema inference rules

---

pom.xml
sqrl-tools/sqrl-cli/dockerrun.sh
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/DatasqrlCMD.java
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/AbstractCommand.java
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/FeatureFlag.java
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/RootCommand.java
sqrl-tools/sqrl-cli/src/test/java/com/datasqrl/cmd/TestCmd.java

Fixes #226
Also removes the feature flags

Set status code on error

---

.github/workflows/docker.yml
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/AbstractCompilerCommand.java
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/DiscoverCommand.java
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/compile/DockerCompose.java
sqrl-tools/sqrl-cli/src/test/java/com/datasqrl/cmd/TestCmd.java

…ich gets passed to the generated docker-compose template. Also makes directories absolute in the discovery.

Fixes #316

---

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/util/PrimaryKeyMap.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/util/SelectIndexMap.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/rules/AnnotatedLP.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/rules/SQRLConverter.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/rules/SQRLLogicalPlanRewriter.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/AddedColumn.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/CalciteTableFactory.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/ProxyImportRelationalTable.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/QueryRelationalTable.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/ScriptRelationalTable.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/SortOrder.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/table/VirtualRelationalTable.java

Allow structured types in LPConverter

---

sqrl-base/src/main/java/com/datasqrl/serializer/Deserializer.java
sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar/pom.xml
sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-jar/src/main/java/com/datasqrl/FlinkMain.java
sqrl-tools/sqrl-cli/dockerrun.sh
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/compile/DockerCompose.java

This reverts commit fdc5c1b814c4c4de94e4743410fc1038f7f84527.

Revert "Encode flink plan as argument for submission (#375)"

---

sqrl-io/sqrl-io-core/src/main/java/com/datasqrl/loaders/DataSource.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/packager/preprocess/Preprocessor.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/util/FileUtil.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/loaders/ObjectLoaderImpl.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/util/GenerateDataSystemConfig.java
sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/preprocess/DataSystemPreprocessor.java
sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/preprocess/TablePreprocessor.java

Make data system filename more flexible to avoid issue with typos.

---

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/schema/sql/SqlBuilders.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/schema/sql/SqlNodeUtil.java

Have AND only take 2 conditions

---

sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/generate/ArgumentGenerator.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/inference/SqrlSchemaForInference.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/generate/SchemaGeneratorTest.java
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testAliased.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testImportWithDifferentCapitalization.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testJson.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testNestedNoPrimaryKey.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testNestedPrimaryKey.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testNestedTable.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorTest/testPrimaryKey.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceErrorsTest/generateSchemaTest.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/c360-full.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/c360-orderstats.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/c360-recommend.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/clickstream-teaser.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/metrics-function.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/nutshopv1-small.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/nutshopv2-small.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/quickstart-teaser-local.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/repo.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest/sensors-teaser.txt

Premute only primary keys (#417)

---

sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-core/src/main/java/com/datasqrl/serializer/Base64Deserializer.java

Fixes the deserializer so it has access to user level classloader so flink can access fat jar classes

Use flink's classloader for base64 deserializer

---

sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/APIConnectorManagerImpl.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/inference/SchemaBuilder.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/inference/SchemaInference.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/inference/SchemaInferenceModel.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/util/GraphqlCheckUtil.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/IntegrationTestSettings.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/AbstractSchemaInferenceModelTest.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/GraphQLMutationExtractionTest.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/SchemaInferenceErrorsTest.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/SchemaInferenceMutationErrorTest.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/MockAPIConnectorManager.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/QuerySnapshotTest.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/ResolveTest.java
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceErrorsTest/invalidFieldTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceErrorsTest/structuralObjectTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceErrorsTest/subscriptionArrayTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceErrorsTest/tooManyFields.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceMutationErrorTest/subscriptionArrayTest.txt
sqrl-planner/sqrl-planner-schema-flexible/src/main/java/com/datasqrl/schema/converters/RelDataTypePrimitiveToFlexibleType.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractPhysicalSQRLIT.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractQuerySQRLIT.java
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/compile/Compiler.java
sqrl-tools/sqrl-cli/src/test/resources/snapshots/com/datasqrl/cmd/TestCmd/compileSubscriptionsInvalidGraphql.txt

Support array types for subscriptions

---

sqrl-base/src/main/java/com/datasqrl/util/NameUtil.java
sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/Packager.java
sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/Preprocessors.java
sqrl-tools/sqrl-packager/src/test/resources/snapshots/com/datasqrl/packager/PackagerTest/dependencyResolution.txt
sqrl-tools/sqrl-packager/src/test/resources/snapshots/com/datasqrl/packager/PackagerTest/testRemoteRepository.txt

Canonicalize path to lowercase for build dir

---

sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/QuerySnapshotTest.java
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonArrayTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonArrayWithEmptyValues.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonArrayWithMixedDataTypes.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonArrayWithNestedArrays.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonArrayWithNulls.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExistsTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithArrayPath.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithComplexJsonPath.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithDefaultBoolean.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithDefaultInteger.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithDefaultNull.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithDefaultString.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithEmptyJson.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithInvalidJsonPath.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithNonexistentPath.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonExtractWithNumericDefault.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonObjectTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonObjectWithEmptyKeys.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonObjectWithMixedDataTypes.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonObjectWithNestedObjects.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonObjectWithNulls.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QueryConversionTest/jsonQueryTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/duplicateImportTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/importDuplicateAliasTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/replaceJoinDeclarationTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/replaceRelationshipTest.txt
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/validateMultiplePKWarning.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/JsonConversionTest/jsonExtractWithInvalidJsonPath.txt

Fix duplicate error messages in tests, remove old snapshots

---

sqrl-execute/sqrl-execute-http/sqrl-execute-http-core/src/main/java/com/datasqrl/graphql/server/BuildGraphQLEngine.java
sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/graphql/inference/SchemaInference.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/SchemaInferenceMutationErrorTest.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/io/TestDataSetMonitoringIT.java
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/graphql/inference/SchemaInferenceMutationErrorTest/nonMatchingInputAndOutputTypes.txt

Allow empty query type

---

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/SqrlToSql.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/visitor/SqlNodeVisitor.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/visitor/SqlRelationVisitor.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/validate/ScriptValidator.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/validate/SqrlToValidatorSql.java
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/QuerySnapshotTest.java
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/orderOnUnion.txt

Support ordered unions

---

sqrl-examples/books/recommendation.schema.graphqls
sqrl-examples/books/recommendation.sqrl
sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/generate/AbstractSchemaGeneratorTest.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/graphql/generate/SchemaGeneratorUseCaseTest.java

Fix book examples

---

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/flink/function/BridgingSqlAggregateFunction.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/flink/FlinkPhysicalIT.java
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/flink/FlinkPhysicalIT/jsonAggTest.txt

Add stub agg implementor (#453)

---

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/function/FlinkUdfNsObject.java
sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/jsonTest.txt
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/flink/FlinkPhysicalIT.java
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/flink/FlinkPhysicalIT/flinkFunctionRenameTest.txt

Fixes a missing function name issue when trying to run UDFs that are aliased.

Use alias name for udfs

---

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/PlannerRules.java
sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/QueryPlanner.java

Register rules intentionally to resolve infinite loop in enumberable

---

sqrl-tools/sqrl-cli/Dockerfile

version 14, verified inside container with psql

install pgvector extension for postgres

---

sqrl-lib/sqrl-json/sqrl-json-execute/src/main/java/com/datasqrl/json/JsonFunctions.java
sqrl-lib/sqrl-json/sqrl-json-execute/src/test/java/com/datasqrl/json/JsonFunctionsTest.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/JsonConversionTest.java
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/JsonConversionTest/jsonArrayAggNull.txt

Update json functions to handle nulls

---

sqrl-tools/sqrl-cli/pom.xml
sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/PackageBootstrap.java
sqrl-tools/sqrl-cli/src/test/java/com/datasqrl/cmd/PackageBootstrapTest.java

Favor local profile during repository resolution

---

sqrl-planner/src/main/java/com/datasqrl/graphql/inference/GraphqlModelGenerator.java
sqrl-server/sqrl-server-vertx/pom.xml
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/GraphQLServer.java
sqrl-server/sqrl-server-vertx/src/test/java/com/datasqrl/graphql/WriteTest.java
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/conference-conference-package.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/loan-loan-package.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/patient-sensor-patient-sensor-package.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/seedshop-mutation-seedshop-mutation-package.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/sensors-mutation-sensors-mutation-package.txt

Partially resolves #564 
Created #624 to resolve the architectural refactor

Move kafka config to vertx

---

sqrl-calcite/src/main/java/com/datasqrl/util/FileUtil.java
sqrl-calcite/src/test/java/com/datasqrl/util/FileUtilTest.java

Use Path for filename resolution.

---

profiles/default/package.json
sqrl-base/src/main/java/com/datasqrl/config/PackageConfiguration.java
sqrl-tools/sqrl-config/src/main/java/com/datasqrl/config/PackageConfigurationImpl.java
sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/repository/Publication.java
sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/repository/RemoteRepositoryImplementation.java
sqrl-tools/sqrl-packager/src/test/java/com/datasqrl/packager/config/ConfigurationTest.java
sqrl-tools/sqrl-packager/src/test/resources/package-configtest.json

Update CLI to Conform to API Changes for Topic Handling

---

sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/AbstractCompilerCommand.java

Closes #658 [658](https://github.com/DataSQRL/sqrl/issues/658)
This was missed because our TestCmd tests are currently broken and doesn't have the --api flag. We should reintroduce them.

Fixes api generation

---

sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/repository/RemoteRepositoryImplementation.java

The original call use of the library has a content length of 25k

Change http call for remote repository

---

sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/schema/constraint/Cardinality.java
sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/schema/input/external/FieldDefinition.java
sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/schema/input/external/FieldTypeDefinition.java
sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/schema/input/external/FieldTypeDefinitionImpl.java
sqrl-planner/src/main/java/com/datasqrl/io/schema/flexible/external/SchemaImport.java

Not in the 'tests', but just a key. 
cardinality:
min: 1
max: 1000

Fix cardinality constraint

---

sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/format/FlexibleSchemaDelegate.java
sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/schema/type/basic/SimpleBasicType.java
sqrl-flink-lib/sqrl-flexible-json/src/main/java/com/datasqrl/schema/type/basic/TimestampType.java
sqrl-planner/src/main/java/com/datasqrl/plan/table/TableConverter.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/UseCasesFullIT.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/UseCasesIT.java
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/logging-kafka-logging-kafka-package.txt
sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/logging/it-kafka/circlesource/reuseddata.table.json
sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/logging/it-kafka/logging-kafka.sqrl
sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/logging/it-kafka/package.json
sqrl-tools/sqrl-run/src/main/java/com/datasqrl/DatasqrlRun.java

Add metadata timestamp format for flexible json

---

pom.xml
sqrl-server/sqrl-server-core/src/main/java/com/datasqrl/graphql/server/GraphQLEngineBuilder.java
sqrl-server/sqrl-server-vertx/pom.xml
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/GraphQLServer.java
sqrl-server/sqrl-server-vertx/src/test/java/com/datasqrl/graphql/WriteTest.java
sqrl-tools/sqrl-run/src/main/java/com/datasqrl/DatasqrlRun.java

This can be expanded out to be driven by configuration in the future.

Add prometheus metrics endpoint

---

sqrl-calcite/src/main/java/com/datasqrl/calcite/SqrlToSql.java
sqrl-testing/sqrl-integration-tests/src/test/resources/dagplanner/distinctTest.sqrl
sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/DAGPlannerTest/distinctTest.txt

Fix distinct casing

---

sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/VertxContext.java
sqrl-server/sqrl-server-vertx/src/test/java/com/datasqrl/graphql/VertxContextTest.java

Fix null values for case insensitive datafetcher (#871)

---

.github/workflows/docker.yml

Run unit tests on main

---

sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/repository/RemoteRepositoryImplementation.java

Trying to get more information when these happen:
```
$ docker datasqrl/cmd:v0.5.6 compile
output:
Compiling...this takes about 10 seconds
java.net.http.HttpConnectTimeoutException: HTTP connect timed out
at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:555)
at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
at com.datasqrl.packager.repository.RemoteRepositoryImplementation.getDependencyInfo(RemoteRepositoryImplementation.java:137)
at com.datasqrl.packager.repository.RemoteRepositoryImplementation.getLatestDependencyInfo(RemoteRepositoryImplementation.java:150)
at com.datasqrl.packager.repository.RemoteRepositoryImplementation.resolveDependency(RemoteRepositoryImplementation.java:119)
at …
```

Include url on timeout exceptions

---

sqrl-planner/src/main/java/com/datasqrl/datatype/flink/avro/AvroFlinkFormatTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/csv/CsvFlinkFormatTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/csv/FlexibleCsvFlinkFormatTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/iceberg/IcebergDataTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/jdbc/FlinkPostgresDataTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/jdbc/FlinkSqrlPostgresDataTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/json/FlexibleJsonFlinkFormatTypeMapper.java
sqrl-planner/src/main/java/com/datasqrl/datatype/flink/json/JsonFlinkFormatTypeMapper.java

Fix serialize to bytes

---

sqrl-planner/src/main/java/com/datasqrl/graphql/inference/GraphqlModelGenerator.java

Add additional error checking for schema walker

---

sqrl-calcite/src/main/java/com/datasqrl/calcite/SqrlConformance.java

Allow the percent operator for mod

---

sqrl-server/sqrl-server-vertx/pom.xml
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/SqrlLauncher.java

Resolves #1011
Note: this changes the config directory to better support mapping in configs

Set prometheus metrics by default, support setting conf directory

---

sqrl-planner/src/main/java/com/datasqrl/functions/vector/StdVectorLibraryImpl.java

Revert "Add DoubleToVector to the std library"

---

docs/datasqrl-spec.md
docs/sqrl-spec.md

- Fixings
- Table types details
- Relationships details
@henneberger @mbroecheler PTAL

Improve Specifications documentation

---

sqrl-server/sqrl-server-core/src/main/java/com/datasqrl/graphql/server/Context.java
sqrl-server/sqrl-server-core/src/main/java/com/datasqrl/graphql/server/GraphQLEngineBuilder.java
sqrl-server/sqrl-server-core/src/main/java/com/datasqrl/graphql/server/RootGraphqlModel.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/GraphQLServer.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/JsonEnvVarDeserializer.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/MutationConfigurationImpl.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/SqrlLauncher.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/SqrlObjectMapper.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/SubscriptionConfigurationImpl.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/VertxContext.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/VertxJdbcClient.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/VertxQueryExecutionContext.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/io/SinkConsumer.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/io/SinkProducer.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/postgres_log/PostgresListenNotifyConsumer.java
sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/type/SqrlVertxScalars.java

- some refactorings or duplicated code and some cleaning
- added some javadocs to major classes of sqrl-server-core and sqrl-server-vertx modules
- started to add a counter for pages and non-pagedjdbc queries.
This PR is not ready for review, just used as a base for discussion if needed.
@mbroecheler @henneberger PTAL

Document server-core server-vertx

---

sqrl-tools/Dockerfile
sqrl-tools/dockerrun.sh
sqrl-tools/redpanda.yaml

duplicate https://github.com/DataSQRL/sqrl/pull/1052

add redpanda volume

---

sqrl-tools/sqrl-cli/pom.xml
sqrl-tools/sqrl-cli/src/main/resources/log4j.properties

Fixes https://github.com/DataSQRL/sqrl/issues/1112

Fix logger configuration

---

documentation/docs/compiler.md
sqrl-tools/sqrl-discovery/src/main/java/com/datasqrl/discovery/preprocessor/DiscoveryPreprocessor.java

also fixes a minor preprocessor bug

Explain ENV vars for local data access

---

pom.xml
sqrl-tools/pom.xml
sqrl-tools/sqrl-run/pom.xml
sqrl-tools/sqrl-run/src/main/java/com/datasqrl/DatasqrlRun.java

Test cases:
https://github.com/DataSQRL/datasqrl-examples/pull/55/

Fix glue and iceberg runtime issues

---

sqrl-tools/Dockerfile

Using same settings as default for flink
https://github.com/apache/flink/blob/92b0e80a34baa90a068e182189a4768496a03d67/flink-dist/src/main/resources/config.yaml#L24

Add extra export and opens

---

sqrl-cli/src/main/java/com/datasqrl/cli/DatasqrlRun.java
sqrl-cli/src/main/java/com/datasqrl/cli/DatasqrlTest.java
sqrl-cli/src/main/java/com/datasqrl/cli/ExecuteCmd.java
sqrl-cli/src/main/java/com/datasqrl/cli/RunCmd.java
sqrl-cli/src/test/java/com/datasqrl/cli/DatasqrlRunTest.java
sqrl-cli/src/test/java/com/datasqrl/cli/ExecuteCmdTest.java
sqrl-cli/src/test/java/com/datasqrl/cli/RunCmdTest.java
sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/FullUseCasesIT.java

Add blocking after Flink job `FINISHED` in case of `run` or `execute`

---

sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/swagger/SwaggerService.java

I tested this manually.
I do not want to hold 0.8.1 further, and include mutation testing to `SwaggerContainerIT` will require a bigger refactor, cause the current setup does not support Kafka on the server img, hence it cannot start up properly.

Map mutation schemas in `SwaggerService`

---

sqrl-planner/src/main/java/com/datasqrl/planner/dag/DAGPlanner.java
sqrl-testing/sqrl-testing-integration/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/multi-batch--package.txt
sqrl-testing/sqrl-testing-integration/src/test/resources/usecases/multi-batch/multi-batch.sqrl
sqrl-testing/sqrl-testing-integration/src/test/resources/usecases/multi-batch/tables/sink_a.table.sql
sqrl-testing/sqrl-testing-integration/src/test/resources/usecases/multi-batch/tables/sink_b.table.sql
sqrl-testing/sqrl-testing-integration/src/test/resources/usecases/multi-batch/tables/source.table.sql

Fix `EXPORT` batch index in multi-batch scripts
