DataSQRL/sqrl

sqrl-engine-flink/src/main/java/com/datasqrl/engine/stream/flink/ExecutionEnvironmentFactory.java, sqrl-engine-flink/src/main/java/com/datasqrl/engine/stream/flink/FlinkEngineConfiguration.java, sqrl-engine-flink/src/main/java/com/datasqrl/engine/stream/flink/LocalFlinkStreamEngineImpl.java, sqrl-engine-flink/src/test/java/com/datasqrl/engine/stream/flink/FlinkEngineConfigurationTest.java, sqrl-engine-flink/src/test/resources/package-flink-conf.json, sqrl-planner/src/main/java/com/datasqrl/plan/local/generate/FileResourceResolver.java
Allow specifying native flink configuration values in the package.json. This would be the same as the flink-conf.yaml except encoded as json.
E.g.:
```
{
"savepoint" : false,
"engineName" : "flink",
"flinkConf" : {
"rest.flamegraph.enabled" : "true",
"taskmanager.memory.network.max": "2gb"
}
}
```
=> Allow specifying a native flink configuration

pom.xml, sqrl-engines/pom.xml, sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/config/PipelineFactory.java, sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/engine/EngineCapability.java, sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/engine/pipeline/SimplePipeline.java, sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/engine/server/ServerEngine.java, sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/engine/stream/StreamEngine.java, sqrl-engines/sqrl-engine-core/src/main/java/com/datasqrl/plan/global/PhysicalDAGPlan.java, sqrl-engines/sqrl-engine-server/pom.xml, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/GenericJavaServerEngine.java, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/GraphqlServerEngineFactory.java, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/LambdaJavaEngineFactory.java, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/LambdaNativeArm64EngineFactory.java, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/LambdaNativeX86EngineFactory.java, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/ServerPhysicalPlan.java, sqrl-engines/sqrl-engine-server/src/main/java/com/datasqrl/engine/server/VertxEngineFactory.java, sqrl-planner/sqrl-planner-local/pom.xml, sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/frontend/SqrlOptimizeDag.java, sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/global/DAGAssembler.java, sqrl-planner/sqrl-planner-local/src/main/java/com/datasqrl/plan/global/DAGPlanner.java, sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/AbstractPhysicalSQRLIT.java, sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/graphql/inference/AbstractSchemaInferenceModelTest.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractQuerySQRLIT.java, sqrl-tools/sqrl-cli/pom.xml, sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/AbstractCompilerCommand.java, sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/compile/Compiler.java, sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/service/PackagerUtil.java, sqrl-tools/sqrl-packager/pom.xml
Adds servlets as a 'server' engine type. Currently it is a no-op for planning since the engine type currently has no local query engine. This is a necessary prerequisite for adding the ability to generate deployment assets.
=> Add servlets as engine types (#231)

sqrl-base/src/main/java/com/datasqrl/model/LogicalStreamMetaData.java
LogicalStreamMetaData was not serializable by flink cluster due to lack of constructor.
=> Fix stream serialization issue

sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-core/src/main/java/com/datasqrl/FlinkEnvironmentBuilder.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractQuerySQRLIT.java
SingleOutputStreamOperator.getSideOutput return a DataStream in 1.15 but a SideOutputDataStream in 1.16. This fixes a method missing exception.
Caused by: java.lang.NoSuchMethodError: 'org.apache.flink.streaming.api.datastream.SideOutputDataStream org.apache.flink.streaming.api.datastream.SingleOutputStreamOperator.getSideOutput(org.apache.flink.util.OutputTag)'
at com.datasqrl.FlinkEnvironmentBuilder.buildStream(FlinkEnvironmentBuilder.java:376)
https://nightlies.apache.org/flink/flink-docs-release-1.15/api/java/org/apache/flink/streaming/api/datastream/SingleOutputStreamOperator.html#getSideOutput-org.apache.flink.util.OutputTag-
https://nightlies.apache.org/flink/flink-docs-release-1.16/api/java/org/apache/flink/streaming/api/datastream/SingleOutputStreamOperator.html#getSideOutput-org. …
=> Fix Flink 1.15 class compatibility bug

sqrl-examples/conference/mysourcepackage/authtokens.schema.yml, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/input/external/SchemaImport.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/AbstractBasicType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/BasicType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/BasicTypeManager.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/BigIntType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/BooleanType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/DoubleType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/IntervalType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/StringType.java, sqrl-io/sqrl-io-schema-flexible/src/main/java/com/datasqrl/schema/type/basic/TimestampType.java, sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/QueryPlanner.java
Moves away from the generalized graphql-esque type mapping to the more concrete sql types. 
Some schemas are published in the registry so the flexible schema is made to be backwards compatible.
Also removes UUID type.
=> Use ungeneralized types for flexible schema and planner

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/SqrlToSql.java, sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/visitor/SqlNodeVisitor.java, sqrl-planner/sqrl-common/src/main/java/com/datasqrl/calcite/visitor/SqlRelationVisitor.java, sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/validate/ScriptValidator.java, sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/validate/SqrlToValidatorSql.java, sqrl-planner/sqrl-common/src/main/java/org/apache/calcite/jdbc/SqrlSchema.java, sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/QuerySnapshotTest.java, sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/callTableFunction.txt, sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/chainedTableFncCallTest.txt, sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/joinTableFncCallTest.txt, sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/lateralJoinTest.txt
Initial support for table functions in SQL. Supports calling sqrl table functions but does not impart sqrl native table paths. 
```
IMPORT ecommerce-data.Orders;
X(@id: Int) := SELECT * FROM Orders WHERE id = @id;
X(@id: Int, @customerid: Int) := SELECT * FROM Orders WHERE id = @id AND customerid = @customerid;
Y(@id: Int) := SELECT * FROM TABLE(X(2));
Z(@id: Int) := SELECT * FROM TABLE(X(2, 3));
```
```
IMPORT ecommerce-data.Orders;
X(@id: Int) := SELECT * FROM Orders WHERE id = @id;
Y(@id: Int) := SELECT * FROM TABLE(X(@id));
Z := SELECT * FROM TABLE(Y(3));
```
=> Support table functions in SQL

sqrl-execute/sqrl-execute-flink/sqrl-execute-flink-core/src/main/java/com/datasqrl/serializer/Base64Deserializer.java, sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/cmd/AbstractCompilerCommand.java, sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/compile/DockerCompose.java, sqrl-tools/sqrl-cli/src/test/resources/snapshots/com/datasqrl/cmd/TestCmd/compileNutshop.txt, sqrl-tools/sqrl-cli/src/test/resources/snapshots/com/datasqrl/cmd/TestCmd/compileNutshopWithSchema.txt, sqrl-tools/sqrl-cli/src/test/resources/snapshots/com/datasqrl/cmd/TestCmd/compileRetail.txt
Follows the recommended practice as outlined here:
https://nightlies.apache.org/flink/flink-docs-stable/docs/deployment/filesystems/plugins/
This copies the presto s3 connector. If using azure, other plugins will need to be copied in. To use, set the aws access key and secret key like the following:
```
flink-jobmanager:
image: flink:1.16.1-scala_2.12-java11
ports:
- "8081:8081"
command: /bin/bash /exec/init-flink.sh jobmanager
environment:
- |
FLINK_PROPERTIES=
jobmanager.rpc.address: flink-jobmanager
- AWS_ACCESS_KEY_ID=...
- AWS_SECRET_KEY=...
volumes:
- ./init-flink.sh:/exec/init-flink.sh
```
=> Copy S3 plugin to flink for docker compose

sqrl-tools/sqrl-cli/src/main/java/com/datasqrl/compile/DockerCompose.java
This removes persistence between docker-compose runes. The volume mapping seems to cause more confusion than help, and it may not be necessary since we don't persist flink state.
Fixes #348
=> Remove volumes from docker compose

sqrl-planner/sqrl-common/src/main/java/com/datasqrl/plan/validate/ScriptValidator.java, sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/QuerySnapshotTest.java, sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/plan/local/analyze/ResolveTest.java, sqrl-planner/sqrl-planner-local/src/test/java/com/datasqrl/util/ScriptBuilder.java, sqrl-planner/sqrl-planner-local/src/test/resources/snapshots/com/datasqrl/plan/local/analyze/QuerySnapshotTest/missingModuleTestTest.txt
Adds a path hint to the error message to build an association between paths and packages.
=> Add path to package error message

sqrl-tools/sqrl-cli/src/test/java/com/datasqrl/cmd/TestCmd.java, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard.graphqls, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard.sqrl, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard/assignment.schema.yml, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard/assignment.table.json, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard/merchant.schema.yml, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard/merchant.table.json, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard/transaction.schema.yml, sqrl-tools/sqrl-cli/src/test/resources/creditcard/creditcard/transaction.table.json
Replicates #479 
Breaking any part of the ProjectFilterTransposeRule -> ProjectMergeRule -> FilterProjectTransposeRule chain will allow it to pass.
=> Add test for infinite loop replication

pom.xml, profiles/flink-1.16/flink/Dockerfile, profiles/flink-1.16/flink/build.gradle, profiles/flink-1.16/vertx/Dockerfile, profiles/flink-1.16/vertx/server-config.json, profiles/flink-1.17/flink/Dockerfile, profiles/flink-1.18/flink/Dockerfile, sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/GraphQLServer.java
Closes #507
By convention, graphql-ws uses the same route as the graphql endpoint, so it is no longer configurable.
=> Add support for graphql-ws websockets

pom.xml, sqrl-planner/pom.xml, sqrl-tools/sqrl-cli/pom.xml, sqrl-tools/sqrl-discovery/pom.xml, sqrl-tools/sqrl-packager/pom.xml
I removed all dependencies that weren't being used in the project. Unfortunately, this didn't significantly reduce the size; it only reduced the jar size by 17MB. If we want to reduce the size more substantially, we need to review other dependencies. We should check how extensively we use a specific dependency, and if it's not used extensively, we should consider dropping it.
=> Slim down CLI jar

pom.xml, sqrl-server/sqrl-server-vertx/pom.xml, sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/GraphQLServer.java, sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/config/ServerConfig.java, sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/config/ServerConfigOptionsConverter.java
This PR adds jwt authentication to the vertx endpoints.
To test it manually, add this section to the server-config.json:
```json
"JWTAuthOptions": {
"pubSecKeys": [
{
"algorithm": "HS256",
"buffer": "dGVzdA=="
}
]
}
```
Call the endpoint with this header:
`Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTY5OTM0ODR9.t0YrUb6K-aiAMpdTQh0-ORwJTdRrrLmiU43oSE1kFkQ`
"buffer" is the BASE64 encoded value of "test".
=> Add jwt token auth to vertx

sqrl-calcite/src/main/java/com/datasqrl/parse/SqrlAstException.java, sqrl-planner/src/main/java/com/datasqrl/graphql/inference/GraphqlSchemaValidator.java, sqrl-planner/src/main/java/com/datasqrl/graphql/util/GraphqlCheckUtil.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractUseCaseTest.java
Fixes two things:
1) Bug in error message for missing type. Fixes #802. 
2) The way we compute the profile path does not work for external use case tests.
=> Fixes #802

sqrl-testing/sqrl-flink-1.18/src/test/java/com/datasqrl/DagPlannerIT.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractAssetSnapshotTest.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/AbstractUseCaseTest.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/DAGPlannerTest.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/DAGWriterJsonTest.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/ExternalUseCaseTest.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/UseCaseCompileTest.java, sqrl-testing/sqrl-integration-tests/src/test/resources/dagplanner/imports-fail.sqrl, sqrl-testing/sqrl-integration-tests/src/test/resources/dagplanner/timestampReassignment.sqrl, sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/DAGPlannerTest/imports-fail.txt, sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/DAGPlannerTest/timestampReassignment.txt
I thought there was an issue with timestamp reassignment, but it behaves correctly: We always fix the first timestamp candidate for a table when there are multiple so the timestamp is unique.
I added a test case to encode this properly.
I also added a test case for missing imports.
=> Timestamp Reassignment

sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/FullUsecasesIT.java
Added a log to the usecases tst runner, it will make reading the logs easier. 
Previously there was no easy way to check which usecase the output belonged to.
=> Adding some more logging to the tests

sqrl-tools/sqrl-config/src/main/java/com/datasqrl/config/SqrlConfigCommons.java, sqrl-tools/sqrl-config/src/main/resources/jsonSchema/publishPackageSchema.json, sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/Publisher.java, sqrl-tools/sqrl-packager/src/test/java/com/datasqrl/packager/PublisherTest.java, sqrl-tools/sqrl-packager/src/test/resources/publisher/invalid/package.json, sqrl-tools/sqrl-packager/src/test/resources/publisher/valid/package.json
This pull request introduces separate validation for the package field during publishing by adding a new method in SqrlConfigCommons, a new JSON schema, and updating the Publisher class to use this new method.
=> Enable Separate Validation for the Package Field During Publishing

sqrl-base/src/main/java/com/datasqrl/module/resolver/FileResourceResolver.java, sqrl-base/src/main/java/com/datasqrl/module/resolver/ResourceResolver.java, sqrl-planner/src/main/java/com/datasqrl/loaders/ObjectLoaderImpl.java, sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/preprocess/JarPreprocessor.java
This pull request introduces consistent handling of jar files for Local and Remote User-Defined Functions (UDFs) by updating the ResourceResolver interface and its implementations. This ensures paths are correctly resolved and utilized throughout the codebase.
Fixes #848
=> Consistent jar handling for Local and Remote UDFs

sqrl-planner/src/main/java/com/datasqrl/functions/flink/FlinkStdLibraryImpl.java
Resolves #949
Like appears to be overloaded in flink to support string types, but we alias string with varchar types so it is not an issue to use our std functions.
=> Exclude like from imported flink functions

sqrl-base/src/main/java/com/datasqrl/module/resolver/FileResourceResolver.java, sqrl-planner/src/main/java/com/datasqrl/loaders/ObjectLoaderImpl.java, sqrl-tools/sqrl-packager/src/main/java/com/datasqrl/packager/preprocess/JarPreprocessor.java
The 'jarPath' is now the name of the jar. We have a duplicate copy to the lib directory but we can clean that up when we start to support translation functions in user provided functions
=> Copy jar to build dir

sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/MutationConfigurationImpl.java
Got the following error while trying to query `event_time` over graphql 
```
09:52:21.203 [vert.x-eventloop-thread-0] WARN  notprivacysafe.graphql.execution.ExecutionStrategy - Can't serialize value (/CreateDeployment/event_time) : Expected something we can convert to 'java.time.OffsetDateTime' but was 'LocalDateTime'.
graphql.schema.CoercingSerializeException: Expected something we can convert to 'java.time.OffsetDateTime' but was 'LocalDateTime'.
at graphql.scalars.datetime.DateTimeScalar$1.serialize(DateTimeScalar.java:51) ~[sqrl-run.jar:0.5.10-SNAPSHOT]
at graphql.scalars.datetime.DateTimeScalar$1.serialize(DateTimeScalar.java:39) ~[sqrl-run.jar:0.5.10-SNAPSHOT]
at graphql.execution.ExecutionStrategy.completeValueForScalar(ExecutionStrategy.java:593) ~[sqrl-run.jar:0.5.10-SNAPSHOT]
at …
```
=> Fix java type for event_time

pom.xml, sqrl-planner/src/main/java/com/datasqrl/v2/analyzer/SQRLLogicalPlanAnalyzer.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/FullUsecasesIT.java, sqrl-testing/sqrl-integration-tests/src/test/java/com/datasqrl/UseCaseCompileTest.java, sqrl-testing/sqrl-integration-tests/src/test/resources/snapshots/com/datasqrl/UseCaseCompileTest/connectors--.txt, sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/avro-schema/package.json, sqrl-testing/sqrl-integration-tests/src/test/resources/usecases/connectors-test/connectors.sqrl, sqrl-tools/sqrl-run/pom.xml
by having a single sqrl/FlinkSQL script that defines a bunch of connectors and formats.
This test is not runnable but if it compiles, we have validation that the dependencies are present.
I added the UseCaseCompileTest.
@velo Can you add a test inside the run module to ensure that the dependencies are present in the runner for execution by datasqrl's run command or in the flink-sql-runner itself? We only need to test that it compiles.
=> Add test for connector/format dependencies

sqrl-tools/sqrl-config/src/main/java/com/datasqrl/config/SqrlConfig.java
Example what it writes exactly with 1 error:
```
java.lang.IllegalArgumentException: Failed to load package configuration:
[FATAL] config/src/test/resources/usecases/sensors/build/package.json$.engines.flink.config: must have at least 1 properties at location [$.engines.flink.config]
at com.datasqrl.error.ErrorMessage.asException(ErrorMessage.java:51)
at com.datasqrl.error.ErrorCollector.exception(ErrorCollector.java:209)
at com.datasqrl.error.ErrorCollector.exception(ErrorCollector.java:202)
at com.datasqrl.config.SqrlConfig.getPackageConfig(SqrlConfig.java:169)
at com.datasqrl.config.SqrlConfig.fromFilesPackageJson(SqrlConfig.java:95)
at com.datasqrl.FullUseCasesIT.useCase(FullUseCasesIT.java:215)
at com.datasqrl.FullUseCasesIT.runTestCaseByName(FullUseCasesIT.java:345)
at …
```
=> Improve error message during package config validation to show the actual error(s)

sqrl-cli/src/main/java/com/datasqrl/cli/DatasqrlRun.java, sqrl-cli/src/main/java/com/datasqrl/cli/ExecuteCmd.java, sqrl-cli/src/main/java/com/datasqrl/cli/RunCmd.java, sqrl-cli/src/main/java/com/datasqrl/cli/TestCmd.java, sqrl-cli/src/test/java/com/datasqrl/cli/ExecuteCmdTest.java, sqrl-cli/src/test/java/com/datasqrl/cli/RunCmdTest.java, sqrl-cli/src/test/java/com/datasqrl/cli/TestCmdTest.java, sqrl-testing/sqrl-container-testing/src/test/java/com/datasqrl/container/testing/SqrlContainerTestBase.java, sqrl-testing/sqrl-container-testing/src/test/java/com/datasqrl/container/testing/SqrlTestContainerIT.java
The common logic could be extracted in a way to avoid duplication and pretty similar unit tests, but for a quick fix IMO this is sufficient.
=> Fix CLI command init and add unit tests

.circleci/config.yml, sqrl-cli/src/main/java/com/datasqrl/cli/AbstractCmd.java, sqrl-cli/src/main/java/com/datasqrl/cli/DatasqrlCli.java, sqrl-cli/src/main/java/com/datasqrl/cli/ExecuteCmd.java, sqrl-cli/src/main/java/com/datasqrl/cli/RunCmd.java, sqrl-cli/src/main/java/com/datasqrl/cli/TestCmd.java, sqrl-cli/src/test/java/com/datasqrl/cli/ExecuteCmdTest.java, sqrl-cli/src/test/java/com/datasqrl/cli/RunCmdTest.java, sqrl-cli/src/test/java/com/datasqrl/cli/TestCmdTest.java
We had an incident earlier `docker run -it -p 8081:8081 -p 8888:8888 --rm -v $PWD:/build [ghcr.io/datasqrl/cmd:dev](http://ghcr.io/datasqrl/cmd:dev) run -c study_stream_package_test.json`
Produced:
```
java.lang.IllegalArgumentException: Failed to load package.json, it is not a regular file
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
at com.datasqrl.util.ConfigLoaderUtils.loadResolvedConfigFromFile(ConfigLoaderUtils.java:93)
at com.datasqrl.util.ConfigLoaderUtils.loadResolvedConfigFromFile(ConfigLoaderUtils.java:88)
at com.datasqrl.util.ConfigLoaderUtils.loadResolvedConfig(ConfigLoaderUtils.java:77)
at com.datasqrl.cli.RunCmd.execute(RunCmd.java:42)
at com.datasqrl.cli.AbstractCmd.run(AbstractCmd.java:47)
at …
```
=> Quick dirty patch to fix datasqrl/cmd:dev

sqrl-cli/src/main/resources/log4j2.properties
Local test with the changed Log4j props:
```
% docker run -it -p 8081:8081 -p 8888:8888 --rm -v $PWD:/build -e OPENAI_API_KEY="$OPENAI_API_KEY" datasqrl/cmd:latest compile -c study_api_package_test.json
Executing SQRL command: "compile" ...
Picked up JAVA_TOOL_OPTIONS: --add-exports=java.base/sun.net.util=ALL-UNNAMED   --add-exports=java.rmi/sun.rmi.registry=ALL-UNNAMED   --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED   --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED   --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED   --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED   --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED   --add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED …
```
=> Ignore Flink TypeExtractor INFO level logs

sqrl-planner/src/main/java/com/datasqrl/error/CollectedException.java, sqrl-planner/src/main/java/com/datasqrl/error/ErrorCollector.java, sqrl-planner/src/main/java/com/datasqrl/error/ErrorMessage.java
Before:
```
java.lang.IllegalArgumentException: Default configuration not found
at com.datasqrl.error.ErrorMessage.asException(ErrorMessage.java:51)
at com.datasqrl.error.ErrorCollector.exception(ErrorCollector.java:209)
at com.datasqrl.error.ErrorCollector.exception(ErrorCollector.java:202)
at com.datasqrl.util.ConfigLoaderUtils.loadUnresolvedConfig(ConfigLoaderUtils.java:211)
at com.datasqrl.util.ConfigLoaderUtilsTest.asd(ConfigLoaderUtilsTest.java:208)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
After:
```
java.lang.IllegalArgumentException: Default configuration not found
at com.datasqrl.util.ConfigLoaderUtils.loadUnresolvedConfig(ConfigLoade …
```
=> Trim collected error stack trace to start with root cause

sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/RestBridgeVerticle.java
• Add missing ctx.end() call for GraphQL error responses in RestBridgeVerticle
• Verify error responses are properly terminated
• Test GraphQL operations with validation errors
=> Fix RestBridgeVerticle error response handling

.circleci/config.yml, Dockerfile.mcp-inspector, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/DetailedRequestTracer.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/HttpServerVerticle.java, sqrl-server/sqrl-server-vertx/src/main/java/com/datasqrl/graphql/SqrlLauncher.java, sqrl-testing/sqrl-container-testing/src/test/java/com/datasqrl/container/testing/ExternalRedpandaContainerIT.java, sqrl-testing/sqrl-container-testing/src/test/java/com/datasqrl/container/testing/SqrlContainerTestBase.java, sqrl-testing/sqrl-container-testing/src/test/java/com/datasqrl/container/testing/VertxContainerIT.java
Add test to verify `DATASQRL_TRACE_REQUESTS=true` logs GraphQL request bodies
=> Add container tests for HTTP request tracing functionality

Dockerfile.mcp-inspector
It seems the `node` minimum version requirement for `npm@11` changed to `20`, and that broke the MCP docker img.
Error from CircleCI:
```
=> ERROR [linux/amd64 2/4] RUN npm install -g npm@11.4.2 &&     npm inst  0.8s
=> CANCELED [linux/arm64 2/4] RUN npm install -g npm@11.4.2 &&     npm i  0.7s
------
> [linux/amd64 2/4] RUN npm install -g npm@11.4.2 &&     npm install -g @modelcontextprotocol/inspector:
0.603 npm error code EBADENGINE
0.603 npm error engine Unsupported engine
0.603 npm error engine Not compatible with your version of node/npm: npm@11.4.2
0.603 npm error notsup Not compatible with your version of node/npm: npm@11.4.2
0.603 npm error notsup Required: {"node":"^20.17.0 || >=22.9.0"}
0.603 npm error notsup Actual:   {"npm":"10.8.2","node":"v18.20.8"}
0.605 npm error A …
```
=> Fix `node` version in the MCP docker image

sqrl-cli/src/main/java/com/datasqrl/cli/AbstractCmd.java, sqrl-cli/src/main/java/com/datasqrl/compile/CompilationProcess.java, sqrl-cli/src/main/java/com/datasqrl/packager/Packager.java, sqrl-planner/src/main/java/com/datasqrl/config/PipelineFactory.java, sqrl-planner/src/main/java/com/datasqrl/engine/pipeline/EngineStage.java, sqrl-planner/src/main/java/com/datasqrl/engine/pipeline/ExecutionPipeline.java, sqrl-planner/src/main/java/com/datasqrl/engine/pipeline/ExecutionStage.java, sqrl-planner/src/main/java/com/datasqrl/engine/pipeline/SimplePipeline.java, sqrl-planner/src/main/java/com/datasqrl/engine/server/GenericJavaServerEngine.java, sqrl-planner/src/main/java/com/datasqrl/plan/global/JdbcIndexOptimization.java, sqrl-planner/src/main/java/com/datasqrl/plan/global/PipelineDAGExporter.java, sqrl-planner/src/main/java/com/datasqrl/plan/global/StageAnalysis.java, sqrl-planner/src/main/java/com/datasqrl/plan/rules/IdealExecutionStage.java, sqrl-planner/src/main/java/com/datasqrl/planner/SqlScriptPlanner.java, sqrl-planner/src/main/java/com/datasqrl/planner/analyzer/cost/SimpleCostAnalysisModel.java, sqrl-planner/src/main/java/com/datasqrl/planner/dag/DAGPlanner.java, sqrl-planner/src/main/java/com/datasqrl/planner/dag/nodes/PipelineNode.java, sqrl-testing/sqrl-testing-integration/src/test/java/com/datasqrl/EngineValidationTest.java, sqrl-testing/sqrl-testing-integration/src/test/resources/engine-validation/invalidPackage-fail.sqrl, sqrl-testing/sqrl-testing-integration/src/test/resources/engine-validation/package.json, sqrl-testing/sqrl-testing-integration/src/test/resources/snapshots/com/datasqrl/EngineValidationTest/invalidPackage-fail.txt
- Validate query engine presence when table format engine is configured in `SimplePipeline`
- `SimplePipeline` is part of the Guice inject flow, so added some extra handling logic in `AbstractCmd` to properly present the validation error there
- Added `EngineValidationTest`
- Some general refactor, removing dead code, updating lombok value class to `record`
=> Validate query engine presence when table format engine is configured

sqrl-cli/src/main/java/com/datasqrl/cli/DatasqrlRun.java, sqrl-cli/src/main/java/com/datasqrl/util/SqrlInjector.java, sqrl-cli/src/test/java/com/datasqrl/engine/server/GenericJavaServerEngineTest.java, sqrl-cli/src/test/java/com/datasqrl/packager/config/ServerConfigTemplateTest.java, sqrl-planner/src/main/java/com/datasqrl/config/ExecutionEnginesHolder.java, sqrl-planner/src/main/java/com/datasqrl/config/QueryEngineConfigConverter.java, sqrl-planner/src/main/java/com/datasqrl/config/QueryEngineConfigConverterImpl.java, sqrl-planner/src/main/java/com/datasqrl/engine/database/QueryEngine.java, sqrl-planner/src/main/java/com/datasqrl/engine/database/relational/DuckDBEngine.java, sqrl-planner/src/main/java/com/datasqrl/engine/database/relational/SnowflakeEngine.java, sqrl-planner/src/main/java/com/datasqrl/engine/server/GenericJavaServerEngine.java, sqrl-planner/src/main/java/com/datasqrl/engine/server/VertxEngineFactory.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/HttpServerVerticle.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/CorsHandlerOptions.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/KafkaConfig.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/ServerConfig.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/ServerConfigUtil.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/ServletConfig.java, sqrl-server/sqrl-server-vertx-base/src/main/java/com/datasqrl/graphql/config/SwaggerConfig.java, sqrl-server/sqrl-server-vertx-base/src/test/java/com/datasqrl/graphql/config/ServerConfigTest.java
- Remove the `JsonObject` boilerplate from our custom `ServerConfig` classes and use Jackson to ser/deser instead
- Add `QueryEngineConfigConverter` to generalize query engine config conversion between `package.json` and the `server-config.json` format
Fixes #1483
Fixes #1484
=> Use Jackson instead of Vert.x `JsonObject` in the server config

sqrl-cli/src/main/java/com/datasqrl/cli/AbstractCompileCmd.java, sqrl-cli/src/main/java/com/datasqrl/util/JBangRunner.java, sqrl-cli/src/main/java/com/datasqrl/util/SqrlInjector.java
If we run an SQRL command programmatically by one of our integration test classes (e.g. `DAGPlannerTest`) `JBangRunner` will be init by Guice and its ctor checks for binary availability, which in my case slowed the internal test exec that uses preprocessors a lot.
- Modified JBang availability check to not run at class instantiation, but the first `isJBangAvailable()` call, so `JBangRunner` will not trigger native `Process` exec right away when Guice sets things up
- Added an internal `DisabledRunner` so internal tests that actually use preprocessors, but will not require JBang at all will not spend significant time figuring out if it exists on the system or not, just to not use it afterwards.
=> Disable JBang runner in case of internal test execution

sqrl-cli/src/test/resources/profiles/profile1/docker-compose.yml
The traditional Bitnami images will no longer be available in their current form. 
They are being archived in the legacy repository so that teams have time to migrate either to their own maintained images or to the new secure catalog
ref: 
- https://github.com/bitnami/containers/issues/83267
=> chore: switch kafka base image from bitnami to bitnamilegacy

sqrl-cli/src/main/java/com/datasqrl/cli/DatasqrlRun.java
This is now done by the Flink SQL runner, so it is redundant to call it here too.
=> Remove Flink `FileSystem.initialize` call from `DatasqrlRun`
